### ISSUE TITLE
uhf.py has wrong uart

### ISSUE THREAD

**Issue by MisterC925** [sbcshop/ArdiPi_Software#1]
The version of uhf.py here uses UART1 instead of UART0.

Using the uhf.py from the separate shield repository worked but I only found it after a lot of hair pulling.

Thanks

**Comment by MisterC925** [comment]
It's also unclear if pin 4 or 5 needs to be high or low to enable the module since the source here says 4 and the source in the shield repository says 5, and the specs say high to enable but the code says low to enable.

I'm pretty sure it's low to enable since it works but clarification would be great.

**Comment by sbcshop3** [comment]
Updated please try with new uhf.py 
To enable it should be low signal to activate UHF module.
